name: Greeting for PR's and Issues
on: [pull_request_target, issues]
jobs:
  greetings:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
          issue-message: "It's great having you contribute to this project. Welcome to the club 🔥"
          pr-message: "It's great having you contribute to this project. Welcome to the club 🤓"